apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-v2
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: node-app
      version: v2

  template:
    metadata:
      labels:
        app: node-app
        version: v2

    spec:
      containers:
        - name: node-app
          image: hashicorp/http-echo
          args:
            - "-text=Hello from DevSecOps Platform V2 🔥"
          ports:
            - containerPort: 5678

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
