apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: node-app
  namespace: default

spec:
  replicas: 3

  selector:
    matchLabels:
      app: node-app

  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: hashicorp/http-echo
        args:
          - "-text=Hello from Rollout 🚀"
        ports:
        - containerPort: 5678
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

  strategy:
    canary:
      canaryService: node-app-canary
      stableService: node-app-stable

      trafficRouting:
        istio:
          virtualService:
            name: node-app-vs
            routes:
              - primary

      steps:
      - setWeight: 10
      - pause: { duration: 30s }

      - setWeight: 30
      - pause: { duration: 30s }

      - setWeight: 60
      - pause: { duration: 30s }

      - setWeight: 100
