apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: main-routing
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway

  http:

  # 🎯 Node app traffic with CANARY + FAILURE
  - match:
    - uri:
        prefix: /node

    fault:
      delay:
        percentage:
          value: 20   # only affect V2 traffic approx
        fixedDelay: 5s

    route:
    - destination:
        host: node-app.default.svc.cluster.local
        subset: v1
        port:
          number: 80
      weight: 80

    - destination:
        host: node-app.default.svc.cluster.local
        subset: v2
        port:
          number: 80
      weight: 20

  # 🎯 Default route (nginx)
  - route:
    - destination:
        host: nginx-app-nginx-chart.default.svc.cluster.local
        port:
          number: 80
