apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-oss
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: https://github.com/jamesilse-solo/platform-gitops.git
    targetRevision: ambient-agentgateway
    path: agentgateway-oss-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
