apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-config
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: git@github.com:maheshnaganna1994-lang/platform-gitops.git
    targetRevision: ambient-agentgateway
    path: agentgateway
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
