apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: git@github.com:maheshnaganna1994-lang/platform-gitops.git
    targetRevision: main
    path: nginx-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  # --- ADD THE FIX HERE ---
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
