apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd

spec:
  project: platform-project

  source:
    repoURL: https://github.com/maheshnaganna1994-lang/platform-gitops
    targetRevision: main
    path: apps/node-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
