apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-policies
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: https://github.com
    path: policies
    targetRevision: main
  destination:
    server: https://default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

