apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nginx-chart
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
