apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0   # 🔥 TEMP allow all egress
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
