apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-limits
      match:
        resources:
          kinds:
            - Deployment
      exclude:
        resources:
          namespaces:
            - kube-system
            - argocd
            - kyverno
      validate:
        message: "CPU and Memory limits are required"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - resources:
                      limits:
                        cpu: "?*"
                        memory: "?*"
